development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: income_management_dev
  pool: 5
  username: postgres
  password: welcome1
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: income_management_test
  pool: 5
  username: postgres
  password: welcome1
production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: income_management_prod
  pool: 5
  username: postgres
  password: welcome1